import RestaurantNavBar from '@/app/restaurant/[slug]/components/RestaurantNavBar'
import Title from '@/app/restaurant/[slug]/components/Title'
import Rating from '@/app/restaurant/[slug]/components/Rating'
import Description from '@/app/restaurant/[slug]/components/Description'
import Image from '@/app/restaurant/[slug]/components/Image'
import Review from '@/app/restaurant/[slug]/components/Review'
import ReservationCard from '@/app/restaurant/[slug]/components/ReservationCard'
import { Metadata } from 'next'
import { PrismaClient } from '.prisma/client'

const prisma = new PrismaClient()

export const metadata: Metadata = {
  title: 'Restaurant page',
  description: 'Generated by create next app',
}

export interface Restaurant {
  id: number
  name: string
  description: string
  slug: string
  images: string[]
}

const getRestaurantBySlug = async (slug: string): Promise<Restaurant> => {
  const restaurant = await prisma.restaurant.findUnique({
    where: {
      slug,
    },
    select: {
      id: true,
      name: true,
      description: true,
      slug: true,
      images: true,
    },
  })

  if (!restaurant) {
    throw new Error()
  }

  return restaurant
}
export default async function RestaurantDetail({ params }: { params: { slug: string } }) {
  // console.log(props.params.slug)
  const restaurant = await getRestaurantBySlug(params.slug)
  return (
    <>
      <div className="bg-white w-[70%] rounded p-3 shadow">
        <RestaurantNavBar slug={restaurant.slug} />
        <Title name={restaurant.name} />
        <Rating />
        <Description description={restaurant.description} />
        <Image images={restaurant.images} />
        <Review />
      </div>
      <div className="w-[27%] relative text-reg">
        <ReservationCard />
      </div>
    </>
  )
}
